# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing kind with cgroup v2
Vagrant.configure("2") do |config|
  # `config.vm.box = "fedora/34-cloud-base"` seems flaky,
  # so we specify the URL explicitly.
  # Mirrors can be found at here: https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/34/x86_64
  config.vm.box = "dummy"
  config.vm.box_url = "https://iad.mirror.rackspace.com/fedora/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-34-1.2.x86_64.vagrant-virtualbox.box"
  memory = 2048
  cpus = 2
  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    # Ensure network-related modules to be loaded
    modprobe tap ip_tables iptable_nat ip6_tables ip6table_nat

    # The moby-engine package included in Fedora lacks support for rootless,
    # So we need to install docker-ce and docker-ce-rootless-extras from the upstream.
    curl -fsSL https://get.docker.com | sh
    # dnf install -y podman-2:3.1.0-1.fc34
    dnf install -y golang-go make kubernetes-client docker-ce-rootless-extras wget
    systemctl enable --now docker

    # libseccomp-dev
    # golang-github-seccomp-containers-golang-dev
    # libgpgme-dev
    # sudo apt install librust-seccomp-sys-dev libseccomp-dev libseccomp2 seccomp


    # install podman
    # wget https://github.com/containers/podman/releases/download/v3.2.1/podman-remote-static.tar.gz
    # tar -xzvf podman-remote-static.tar.gz
    # cp podman-remote-static /usr/bin/podman
    # from https://koji.fedoraproject.org/koji/packageinfo?packageID=26289
    wget https://kojipkgs.fedoraproject.org//packages/podman/3.2.2/1.fc34/x86_64/podman-3.2.2-1.fc34.x86_64.rpm
    dnf localinstall -y podman-3.2.2-1.fc34.x86_64.rpm
    podman info
    # Configuration for rootless: https://kind.sigs.k8s.io/docs/user/rootless/
    mkdir -p "/etc/systemd/system/user@.service.d"
    cat <<EOF >"/etc/systemd/system/user@.service.d/delegate.conf"
    [Service]
    Delegate=yes
    EOF
    systemctl daemon-reload
    loginctl enable-linger vagrant
    SHELL
  end
  config.vm.provision "install-kind", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    make -C /vagrant install INSTALL_DIR=/usr/local/bin
    SHELL
  end
end
